#----------------------------------------------------------------
# Travis-CI configuration for R packages
#
# REFERENCES:
# * Travis CI: https://travis-ci.org/
# * native R support: https://github.com/craigcitro/r-travis
# * examples: https://github.com/craigcitro/r-travis/wiki/Porting-to-native-R-support-in-Travis
# * r-builder: https://github.com/metacran/r-builder
# * covr: https://github.com/jimhester/covr
# * Coveralls: https://coveralls.io/
#
# Validate your .travis.yml file at http://lint.travis-ci.org/
#----------------------------------------------------------------
# sudo: required
# r_binary_packages:
#   - knitr
#   - data.table
#   - RUnit
#   - igraph
#   - ggplot2
#   - Hmisc
#   - mvtnorm
#   - copula
#   - bindata
# r_packages:
#   - copula
# - libgsl0-dev
# - gsl-bin

language: r
sudo: false
cache: packages
warnings_are_errors: false
# r_build_args: "--compact-vignettes"
# r_check_args: "--as-cran"
r_build_args: "--no-build-vignettes --no-manual"
r_check_args: "--no-build-vignettes --no-manual --as-cran"

before_install:
  Rscript -e 'update.packages(ask = FALSE)'
  - export RGL_USE_NULL=TRUE

r_packages:
  - covr
  - copula

r:
  - oldrel
  - release
  - devel

r_github_packages:
  - jimhester/covr

addons:
  apt:
    packages:
      - libicu-dev
      - pandoc

env:
 global:
   - CRAN: http://cran.rstudio.com
   - RGL_USE_NULL=TRUE

after_success:
  - Rscript -e 'covr::coveralls()'

on_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

